//------------------------------------------------------------------------------
// <auto-generated>
//     This file is generated by the resx → Designer tooling. Edit Strings.resx
//     and regenerate via scripts/regenerate-strings-designer.sh.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace InstallerClean.Resources;

using System.Globalization;
using System.Resources;

/// <summary>
/// Strongly-typed accessor over Strings.resx. C# code paths use these
/// properties for compile-time safety; XAML uses {loc:Translate Key}
/// (see TranslateExtension) which resolves the same keys at runtime.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("InstallerClean.ResxGen", "1.0.0.0")]
public static class Strings
{
    private static readonly ResourceManager Manager =
        new("InstallerClean.Resources.Strings", typeof(Strings).Assembly);

    /// <summary>The cached ResourceManager backing every property below.</summary>
    public static ResourceManager ResourceManager => Manager;

    /// <summary>Override the culture used for lookups (otherwise CurrentUICulture).</summary>
    public static CultureInfo? Culture { get; set; }

    private static string Get(string key) =>
        Manager.GetString(key, Culture ?? CultureInfo.CurrentUICulture) ?? key;

    public static string Action_About => Get("Action.About");
    public static string Action_Browse => Get("Action.Browse");
    public static string Action_Cancel => Get("Action.Cancel");
    public static string Action_CheckForUpdates => Get("Action.CheckForUpdates");
    public static string Action_Close => Get("Action.Close");
    public static string Action_Copy => Get("Action.Copy");
    public static string Action_Delete => Get("Action.Delete");
    public static string Action_Details => Get("Action.Details");
    public static string Action_Donate => Get("Action.Donate");
    public static string Action_LeaveStarOnGitHub => Get("Action.LeaveStarOnGitHub");
    public static string Action_MITLicence => Get("Action.MITLicence");
    public static string Action_Move => Get("Action.Move");
    public static string Action_MoveDestinationPlaceholder => Get("Action.MoveDestinationPlaceholder");
    public static string Action_Rescan => Get("Action.Rescan");
    public static string Action_ScanAgain => Get("Action.ScanAgain");
    public static string Automation_BuyMeACuppa => Get("Automation.BuyMeACuppa");
    public static string Automation_CancelOperation => Get("Automation.CancelOperation");
    public static string Automation_CancelScan => Get("Automation.CancelScan");
    public static string Automation_CancelStartupScan => Get("Automation.CancelStartupScan");
    public static string Automation_Close => Get("Automation.Close");
    public static string Automation_CloseInstallerClean => Get("Automation.CloseInstallerClean");
    public static string Automation_ConfirmDelete => Get("Automation.ConfirmDelete");
    public static string Automation_DeleteAllFiles => Get("Automation.DeleteAllFiles");
    public static string Automation_LeaveStarOnGitHub => Get("Automation.LeaveStarOnGitHub");
    public static string Automation_Maximise => Get("Automation.Maximise");
    public static string Automation_Minimise => Get("Automation.Minimise");
    public static string Automation_MoveAllFiles => Get("Automation.MoveAllFiles");
    public static string Automation_MoveDestinationFolder => Get("Automation.MoveDestinationFolder");
    public static string Automation_OperationProgress => Get("Automation.OperationProgress");
    public static string Automation_RescanInstaller => Get("Automation.RescanInstaller");
    public static string Automation_ScanningProgress => Get("Automation.ScanningProgress");
    public static string Automation_StartupScanProgress => Get("Automation.StartupScanProgress");
    public static string Automation_ViewOrphanedFiles => Get("Automation.ViewOrphanedFiles");
    public static string Automation_ViewRegisteredFiles => Get("Automation.ViewRegisteredFiles");
    public static string Body_MainExplanation => Get("Body.MainExplanation");
    public static string Body_NoFileSelected => Get("Body.NoFileSelected");
    public static string Body_NoMetadata => Get("Body.NoMetadata");
    public static string Body_NoPatches => Get("Body.NoPatches");
    public static string Body_NoProductSelected => Get("Body.NoProductSelected");
    public static string Body_PendingReboot => Get("Body.PendingReboot");
    public static string Cli_AdminRequired => Get("Cli.AdminRequired");
    public static string Cli_Cancelled => Get("Cli.Cancelled");
    public static string Cli_Cancelling => Get("Cli.Cancelling");
    public static string Cli_DeletedFiles => Get("Cli.DeletedFiles");
    public static string Cli_DeletingFiles => Get("Cli.DeletingFiles");
    public static string Cli_EventLogDeleteSummary => Get("Cli.EventLogDeleteSummary");
    public static string Cli_EventLogMoveDestinationInsideInstaller => Get("Cli.EventLogMoveDestinationInsideInstaller");
    public static string Cli_EventLogMoveNoDestination => Get("Cli.EventLogMoveNoDestination");
    public static string Cli_EventLogMoveSummary => Get("Cli.EventLogMoveSummary");
    public static string Cli_EventLogPendingRebootBlocked => Get("Cli.EventLogPendingRebootBlocked");
    public static string Cli_EventLogScanFound => Get("Cli.EventLogScanFound");
    public static string Cli_EventLogScanNoOrphans => Get("Cli.EventLogScanNoOrphans");
    public static string Cli_FoundOrphans => Get("Cli.FoundOrphans");
    public static string Cli_GenericError => Get("Cli.GenericError");
    public static string Cli_Help_Delete => Get("Cli.Help.Delete");
    public static string Cli_Help_Header => Get("Cli.Help.Header");
    public static string Cli_Help_Help => Get("Cli.Help.Help");
    public static string Cli_Help_MoveDefault => Get("Cli.Help.MoveDefault");
    public static string Cli_Help_MovePath => Get("Cli.Help.MovePath");
    public static string Cli_Help_NoteLine1 => Get("Cli.Help.NoteLine1");
    public static string Cli_Help_NoteLine2 => Get("Cli.Help.NoteLine2");
    public static string Cli_Help_NoteLine3 => Get("Cli.Help.NoteLine3");
    public static string Cli_Help_ScanOnly => Get("Cli.Help.ScanOnly");
    public static string Cli_Help_Usage => Get("Cli.Help.Usage");
    public static string Cli_MoveDestinationInsideInstaller => Get("Cli.MoveDestinationInsideInstaller");
    public static string Cli_MovedFiles => Get("Cli.MovedFiles");
    public static string Cli_MovingFiles => Get("Cli.MovingFiles");
    public static string Cli_NoMoveDestination => Get("Cli.NoMoveDestination");
    public static string Cli_NothingToDo => Get("Cli.NothingToDo");
    public static string Cli_PendingRebootBlocked => Get("Cli.PendingRebootBlocked");
    public static string Cli_ScanningInstaller => Get("Cli.ScanningInstaller");
    public static string Cli_UnknownArgument => Get("Cli.UnknownArgument");
    public static string Completion_AllClear => Get("Completion.AllClear");
    public static string Completion_Cleared => Get("Completion.Cleared");
    public static string Completion_DeleteRestoreHint => Get("Completion.DeleteRestoreHint");
    public static string Completion_DeleteSummary => Get("Completion.DeleteSummary");
    public static string Completion_DeleteSummaryWithErrors => Get("Completion.DeleteSummaryWithErrors");
    public static string Completion_MoveRestoreHint => Get("Completion.MoveRestoreHint");
    public static string Completion_MoveSummary => Get("Completion.MoveSummary");
    public static string Completion_MoveSummaryWithErrors => Get("Completion.MoveSummaryWithErrors");
    public static string Completion_NothingToCleanUp => Get("Completion.NothingToCleanUp");
    public static string Completion_PartlyCleared => Get("Completion.PartlyCleared");
    public static string Confirm_DeleteLargeWarning => Get("Confirm.DeleteLargeWarning");
    public static string Confirm_DeleteTitle => Get("Confirm.DeleteTitle");
    public static string Confirm_DeleteToRecycleBin => Get("Confirm.DeleteToRecycleBin");
    public static string Confirm_MoveDestination => Get("Confirm.MoveDestination");
    public static string Confirm_MoveTitle => Get("Confirm.MoveTitle");
    public static string Error_AccessDenied => Get("Error.AccessDenied");
    public static string Error_AccessDeniedDestination => Get("Error.AccessDeniedDestination");
    public static string Error_AdminRequiredBody => Get("Error.AdminRequiredBody");
    public static string Error_AdminRequiredTitle => Get("Error.AdminRequiredTitle");
    public static string Error_CannotWriteFolder => Get("Error.CannotWriteFolder");
    public static string Error_DestinationInsideInstaller => Get("Error.DestinationInsideInstaller");
    public static string Error_DestinationMissing => Get("Error.DestinationMissing");
    public static string Error_InstallerDbEmpty => Get("Error.InstallerDbEmpty");
    public static string Error_InstallerDbUnavailableTitle => Get("Error.InstallerDbUnavailableTitle");
    public static string Error_InvalidDestinationTitle => Get("Error.InvalidDestinationTitle");
    public static string Error_IOFailure => Get("Error.IOFailure");
    public static string Error_IOWriteDestination => Get("Error.IOWriteDestination");
    public static string Error_MissingSourceFile => Get("Error.MissingSourceFile");
    public static string Error_MoveIntoInstaller => Get("Error.MoveIntoInstaller");
    public static string Error_MsiAccessDenied => Get("Error.MsiAccessDenied");
    public static string Error_MsiNonSuccess => Get("Error.MsiNonSuccess");
    public static string Error_NotEnoughSpaceBody => Get("Error.NotEnoughSpaceBody");
    public static string Error_NotEnoughSpaceTitle => Get("Error.NotEnoughSpaceTitle");
    public static string Error_NoUniqueFilename => Get("Error.NoUniqueFilename");
    public static string Error_PathTooLong => Get("Error.PathTooLong");
    public static string Error_ShellRecycleFailed => Get("Error.ShellRecycleFailed");
    public static string Error_SourceIsReparsePoint => Get("Error.SourceIsReparsePoint");
    public static string Error_UnknownError => Get("Error.UnknownError");
    public static string Error_WriteDestination => Get("Error.WriteDestination");
    public static string Field_Application => Get("Field.Application");
    public static string Field_Author => Get("Field.Author");
    public static string Field_Comment => Get("Field.Comment");
    public static string Field_File => Get("Field.File");
    public static string Field_FileSize => Get("Field.FileSize");
    public static string Field_Keywords => Get("Field.Keywords");
    public static string Field_Patches => Get("Field.Patches");
    public static string Field_ProductName => Get("Field.ProductName");
    public static string Field_Reason => Get("Field.Reason");
    public static string Field_SigningCertificate => Get("Field.SigningCertificate");
    public static string Field_Size => Get("Field.Size");
    public static string Field_Subject => Get("Field.Subject");
    public static string Field_Title => Get("Field.Title");
    public static string Field_UnknownProductName => Get("Field.UnknownProductName");
    public static string FilePicker_ChooseDestinationTitle => Get("FilePicker.ChooseDestinationTitle");
    public static string Plural_Error_Plural => Get("Plural.Error.Plural");
    public static string Plural_Error_Singular => Get("Plural.Error.Singular");
    public static string Plural_File_Plural => Get("Plural.File.Plural");
    public static string Plural_File_Singular => Get("Plural.File.Singular");
    public static string Plural_FileVerb_Plural => Get("Plural.FileVerb.Plural");
    public static string Plural_FileVerb_Singular => Get("Plural.FileVerb.Singular");
    public static string Reason_Orphaned => Get("Reason.Orphaned");
    public static string Reason_Superseded => Get("Reason.Superseded");
    public static string Section_Move_Location => Get("Section.Move.Location");
    public static string Section_Registered_Details => Get("Section.Registered.Details");
    public static string Section_Registered_Patches => Get("Section.Registered.Patches");
    public static string Section_Registered_Products => Get("Section.Registered.Products");
    public static string Startup_AlreadyRunningBody => Get("Startup.AlreadyRunningBody");
    public static string Startup_AlreadyRunningTitle => Get("Startup.AlreadyRunningTitle");
    public static string Startup_ErrorTitle => Get("Startup.ErrorTitle");
    public static string Startup_FailedToStart => Get("Startup.FailedToStart");
    public static string Startup_UnhandledBody => Get("Startup.UnhandledBody");
    public static string Startup_UnhandledTitle => Get("Startup.UnhandledTitle");
    public static string Status_Cancelling => Get("Status.Cancelling");
    public static string Status_CheckingRegistry => Get("Status.CheckingRegistry");
    public static string Status_DeleteCancelled => Get("Status.DeleteCancelled");
    public static string Status_DeleteFailed => Get("Status.DeleteFailed");
    public static string Status_Deleting => Get("Status.Deleting");
    public static string Status_Done => Get("Status.Done");
    public static string Status_EnumeratingProducts => Get("Status.EnumeratingProducts");
    public static string Status_FoundOrphans => Get("Status.FoundOrphans");
    public static string Status_FoundProducts => Get("Status.FoundProducts");
    public static string Status_MoveCancelled => Get("Status.MoveCancelled");
    public static string Status_MoveFailed => Get("Status.MoveFailed");
    public static string Status_Moving => Get("Status.Moving");
    public static string Status_PreparingDestination => Get("Status.PreparingDestination");
    public static string Status_QueryingApi => Get("Status.QueryingApi");
    public static string Status_RegistryScanComplete => Get("Status.RegistryScanComplete");
    public static string Status_ScanAccessDenied => Get("Status.ScanAccessDenied");
    public static string Status_ScanCancelled => Get("Status.ScanCancelled");
    public static string Status_ScanComplete => Get("Status.ScanComplete");
    public static string Status_ScanFailedDb => Get("Status.ScanFailedDb");
    public static string Status_ScanFailedDetails => Get("Status.ScanFailedDetails");
    public static string Status_Scanning => Get("Status.Scanning");
    public static string Status_ScanningCache => Get("Status.ScanningCache");
    public static string Status_StartingScan => Get("Status.StartingScan");
    public static string Summary_MissingFromDisk => Get("Summary.MissingFromDisk");
    public static string Summary_OperationFiles => Get("Summary.OperationFiles");
    public static string Summary_OrphanedToCleanUp => Get("Summary.OrphanedToCleanUp");
    public static string Summary_OrphanedWindow => Get("Summary.OrphanedWindow");
    public static string Summary_RegisteredStillUsed => Get("Summary.RegisteredStillUsed");
    public static string Summary_RegisteredWindow => Get("Summary.RegisteredWindow");
    public static string Tooltip_BuyMeACuppa => Get("Tooltip.BuyMeACuppa");
    public static string Tooltip_Close => Get("Tooltip.Close");
    public static string Tooltip_DeleteDisabledHint => Get("Tooltip.DeleteDisabledHint");
    public static string Tooltip_LeaveStarOnGitHub => Get("Tooltip.LeaveStarOnGitHub");
    public static string Tooltip_Maximise => Get("Tooltip.Maximise");
    public static string Tooltip_Minimise => Get("Tooltip.Minimise");
    public static string Tooltip_MoveDestination => Get("Tooltip.MoveDestination");
    public static string Tooltip_MoveDisabledHint => Get("Tooltip.MoveDisabledHint");
    public static string Tooltip_OpenProjectOnGitHub => Get("Tooltip.OpenProjectOnGitHub");
    public static string Tooltip_Restore => Get("Tooltip.Restore");
    public static string Tooltip_SigningCertificate => Get("Tooltip.SigningCertificate");
    public static string Version_Display => Get("Version.Display");
    public static string Window_About_Title => Get("Window.About.Title");
    public static string Window_ConfirmDelete_Title => Get("Window.ConfirmDelete.Title");
    public static string Window_ConfirmMove_Title => Get("Window.ConfirmMove.Title");
    public static string Window_Main_Title => Get("Window.Main.Title");
    public static string Window_Orphaned_Title => Get("Window.Orphaned.Title");
    public static string Window_Registered_Title => Get("Window.Registered.Title");
}
