#!/usr/bin/env bash
# Regenerates src/InstallerClean.Core/Resources/Strings.Designer.cs from
# Strings.resx. Run after adding, removing, or renaming a key in the
# .resx so the typed accessor surface stays in sync.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
RESX=$ROOT/src/InstallerClean.Core/Resources/Strings.resx
OUT=$ROOT/src/InstallerClean.Core/Resources/Strings.Designer.cs

[[ -f $RESX ]] || { echo "Missing $RESX" >&2; exit 1; }

KEYS=$(grep -oE '<data name="[A-Za-z][A-Za-z0-9._]+' "$RESX" \
         | sed 's|<data name="||' | sort -u)

# The program below is all BEGIN and END, but awk given no input file reads stdin
# whatever its program looks like, so stdin is closed explicitly here: left open by
# the caller, awk blocks there and $OUT is left truncated with no error.
awk -v keys="$KEYS" '
BEGIN {
    print "//------------------------------------------------------------------------------"
    print "// <auto-generated>"
    print "//     This file is generated by the resx \xe2\x86\x92 Designer tooling. Edit Strings.resx"
    print "//     and regenerate via scripts/regenerate-strings-designer.sh."
    print "// </auto-generated>"
    print "//------------------------------------------------------------------------------"
    print ""
    print "#nullable enable"
    print ""
    print "namespace InstallerClean.Resources;"
    print ""
    print "using System.Resources;"
    print "using InstallerClean.Helpers;"
    print ""
    print "/// <summary>"
    print "/// Strongly-typed accessor over Strings.resx. C# code paths use these"
    print "/// properties for compile-time safety; XAML uses {loc:Translate Key}"
    print "/// (see TranslateExtension) which resolves the same keys at runtime."
    print "/// Get and Find are the only two routes from a resx value to a user and"
    print "/// both spend the installer-folder token, which is what lets a string"
    print "/// name the cache folder correctly on a machine whose Windows is not on"
    print "/// C:. scripts/check-cross-key-rules.mjs fails the build on a third."
    print "/// </summary>"
    print "[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"InstallerClean.ResxGen\", \"1.0.0.0\")]"
    print "public static class Strings"
    print "{"
    print "    private static readonly ResourceManager Manager ="
    print "        new(\"InstallerClean.Resources.Strings\", typeof(Strings).Assembly);"
    print ""
    print "    /// <summary>"
    print "    /// The cached ResourceManager backing every property below, reached"
    print "    /// only by the tests that audit the shipped satellites: those read"
    print "    /// whole resource sets, which no per-key door can answer, and they"
    print "    /// need the values raw, token and all."
    print "    /// </summary>"
    print "    internal static ResourceManager ResourceManager => Manager;"
    print ""
    print "    /// <summary>"
    print "    /// The door for every key with an accessor below, XAML included"
    print "    /// (TranslateExtension calls this), which is why the installer-folder"
    print "    /// token is substituted here: a string naming the cache folder is"
    print "    /// correct everywhere by writing it. A missing key falls back to the"
    print "    /// key itself, so a typo shows on screen rather than as a blank."
    print "    /// </summary>"
    print "    internal static string Get(string key) =>"
    print "        InstallerFolderToken.Resolve(Manager.GetString(key, Localisation.UiCulture) ?? key);"
    print ""
    print "    /// <summary>"
    print "    /// The door for a key assembled at runtime, which has no accessor"
    print "    /// below to come through: the satellite-only plural overrides, built"
    print "    /// from a key prefix and a CLDR category. Absent is the ordinary"
    print "    /// answer there and means fall back to the neutral form, so this"
    print "    /// returns null rather than echoing the key back the way Get does."
    print "    /// </summary>"
    print "    internal static string? Find(string key) =>"
    print "        Manager.GetString(key, Localisation.UiCulture) is { } value"
    print "            ? InstallerFolderToken.Resolve(value)"
    print "            : null;"
    print ""

    n = split(keys, arr, "\n")
    for (i = 1; i <= n; i++) {
        key = arr[i]
        if (key == "") continue
        prop = key
        gsub(/\./, "_", prop)
        print "    public static string " prop " => Get(\"" key "\");"
    }
}
END {
    print "}"
}
' </dev/null > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
