#!/usr/bin/env bash
# Regenerates src/InstallerClean/Resources/Strings.Designer.cs from
# Strings.resx. Run after adding, removing, or renaming a key in the
# .resx so the typed accessor surface stays in sync.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
RESX=$ROOT/src/InstallerClean/Resources/Strings.resx
OUT=$ROOT/src/InstallerClean/Resources/Strings.Designer.cs

[[ -f $RESX ]] || { echo "Missing $RESX" >&2; exit 1; }

KEYS=$(grep -oE '<data name="[A-Za-z][A-Za-z0-9._]+' "$RESX" \
         | sed 's|<data name="||' | sort -u)

awk -v keys="$KEYS" '
BEGIN {
    print "//------------------------------------------------------------------------------"
    print "// <auto-generated>"
    print "//     This file is generated by the resx \xe2\x86\x92 Designer tooling. Edit Strings.resx"
    print "//     and regenerate via scripts/regenerate-strings-designer.sh."
    print "// </auto-generated>"
    print "//------------------------------------------------------------------------------"
    print ""
    print "#nullable enable"
    print ""
    print "namespace InstallerClean.Resources;"
    print ""
    print "using System.Globalization;"
    print "using System.Resources;"
    print ""
    print "/// <summary>"
    print "/// Strongly-typed accessor over Strings.resx. C# code paths use these"
    print "/// properties for compile-time safety; XAML uses {loc:Translate Key}"
    print "/// (LocExtension) which resolves the same keys at runtime."
    print "/// </summary>"
    print "[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"InstallerClean.ResxGen\", \"1.0.0.0\")]"
    print "public static class Strings"
    print "{"
    print "    private static readonly ResourceManager Manager ="
    print "        new(\"InstallerClean.Resources.Strings\", typeof(Strings).Assembly);"
    print ""
    print "    /// <summary>The cached ResourceManager backing every property below.</summary>"
    print "    public static ResourceManager ResourceManager => Manager;"
    print ""
    print "    /// <summary>Override the culture used for lookups (otherwise CurrentUICulture).</summary>"
    print "    public static CultureInfo? Culture { get; set; }"
    print ""
    print "    private static string Get(string key) =>"
    print "        Manager.GetString(key, Culture ?? CultureInfo.CurrentUICulture) ?? key;"
    print ""

    n = split(keys, arr, "\n")
    for (i = 1; i <= n; i++) {
        key = arr[i]
        if (key == "") continue
        prop = key
        gsub(/\./, "_", prop)
        print "    public static string " prop " => Get(\"" key "\");"
    }
}
END {
    print "}"
}
' > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
